- name: hello world
  hosts: local
  connection: local
  tasks:
  - name: print hello world
    ansible.builtin.debug:
      msg: "Hello world"

#ansible-playbook -i inventory.ini -e ansible_user=ec2-user -e ansible_password=DevOps321 02-hello-world.yaml
