- name: nginx install and run
  hosts: frontend
  tasks:
  - name: install nginx
    ansible.builtin.package:
      name: nginx
      state: present
  - name: start nginx
    ansible.buitin.service:
      name: nginx
      state: started
      enabled: yes


 #ansible install pacakges