- name: play level varaibles
  hosts: local
  connection: local
  vars:
    COURSE: DevOps
    DURATION: 120 hrs
    TRAINER: siva
  tasks:
  - name: print source information
    vars:
      COURSE: Python
    ansible.builtin.debug:
      msg: "hello couser {{ COURSE }} duration {{ DURATION }} with trainer {{ TRAINER}}"
  
  - name: print source information again
    ansible.builtin.debug:
     msg: "hello couser {{ COURSE }} duration {{ DURATION }} with trainer {{ TRAINER}}"