- name: varaibles from the prompt
  hosts: local
  connection: local
  vars_prompt:
  - name: USERNAME
    prompt: Please enter username
    private: true
  - name: PASSWORD
    prompt: enter your password
    private: true
    tasks:
    - name: printing user infor
      ansible.builtin.debug:
        msg: "Hello username is {{ USERNAME}} with password {{ PASSWORD}}"
        