- name: conditions demo
  hosts: local
  connection: local
  vars:
    NUMBER: 34
  tasks:
  - name: print if the given number is less than or equal to 50
    ansible.builtin.debug:
      msg:" given number {{NUMBER }} is less than or equal to 50"
    when: NUMBER < 50
  - name: print if the given number is greather than or equal to 50
    ansible.builtin.debug:
      msg:" given number {{NUMBER }} is greather than or equal to 50"
    when: NUMBER > 50